### PR TITLE
add possibility to set serviceAccountName

### PR DESCRIPTION
**Pull request by severi**
Hey! Would be great if the chart could also support setting the serviceAccountName. This PR adds that possibility

### CODE REVIEW

**Comment by severi** [comment]
Great! Possible to get the new version published to `https://equinor.github.io/helm-charts/charts/` ? :)

**Comment by StianOvrevage** [comment]
Aha, I see you commited to the old repo that should have been deleted. Everything now lives in https://github.com/equinor/helm-charts . Do you mind adding the changes and creating a PR there? There is automatic build and publish of charts using GH actions on that repo.

**Comment by severi** [comment]
haha great, I'll do just that :)

**Comment by severi** [comment]
There you go! https://github.com/equinor/helm-charts/pull/1

**Comment by StianOvrevage** [comment]
Thanks @severi ! Just wondering how you found this repo, is there any links I have forgotten to update to point at the new repo?

**Comment by severi** [comment]
@StianOvrevage really good question :D Probably tried to follow the link from: https://hub.helm.sh/charts/equinor-charts/neo4j-community which has a broken reference to the correct repo in the "Related" section (https://github.com/equinor/helm-charts/charts/neo4j-community doesn't work). So I just opened the equinor github page and searched for neo4j from the repos and ended up in the old repo

**Comment by StianOvrevage** [comment]
Thanks. Fixed the broken link now! And deleting this repo :)

**Pull request merged**
